### ISSUE TITLE
[Bug] error for non ascii chars in path

### ISSUE THREAD

**Issue by derpicknicker1** [qmk/qmk_distro_msys#49]
## Describe the Bug

I have a german 'Umlaut' (ü) in my windows username. qmk setup fails because of that. I can not figure out how to use an other path for `AppData/Local/QMK...`

## Additional Context

```
Wrote configuration to 'C:/Users/FlorianSchütte/AppData/Local/QMK/qmk/qmk.ini'
Error: %s: %s ('ImportError', ImportError("cannot import name 'format_ansi' from 'milc' (C:/QMK_MSYS/mingw64/lib/python3.8/site-packages/milc/__init__.py)"))
Traceback (most recent call last):
  File "C:/QMK_MSYS/mingw64/lib/python3.8/site-packages/qmk_cli/script_qmk.py", line 99, in main
    import qmk.cli  # noqa
  File "X:/qmk_firmware/lib/python/qmk/cli/__init__.py", line 13, in <module>
    from . import doctor
  File "X:/qmk_firmware/lib/python/qmk/cli/doctor.py", line 12, in <module>
    from qmk.questions import yesno
  File "X:/qmk_firmware/lib/python/qmk/questions.py", line 4, in <module>
    from milc import cli, format_ansi
ImportError: cannot import name 'format_ansi' from 'milc' (C:/QMK_MSYS/mingw64/lib/python3.8/site-packages/milc/__init__.py)
```

**Comment by derpicknicker1** [comment]
Forget about this...my fault...

**Comment by jackhumbert** [comment]
Just for posterity & searchability, this specific error is caused by an out-of-date qmk_firmware checkout - [the CLI looks for any folder that might be a qmk_firmware folder](https://github.com/qmk/qmk_cli/blob/b70736a87649cd8012d078d621e94f3da845beb6/qmk_cli/helpers.py#L11), and if you aren't aware of what's in your home folder (I wasn't), you'll get this when you start QMK MSYS.
