### ISSUE TITLE
[Bug]  Invalid return_code: 2816

### ISSUE THREAD

**Issue by DrL3cter** [qmk/qmk_distro_msys#93]
### Describe the Bug

Hey there,

I've got a small problem with my qmk installation. I tried to fix it with a freshly installed version of qmk but that didn't work.
Two weeks ago I compiled a few changes for my ergodox ez and everything went just fine, but after I added an additional KC_LALT Key to my keymap and the attempt to recompile my keymap I got the attached return message.
Since I found no existing information dealing with the return code I would like to know if you have any idea how to fix it?
I tried to compile different keyboards and keymaps, with no changed result.

Best regards

### Additional Context?

![image](https://user-images.githubusercontent.com/91549295/135108877-2ca1ffa0-086b-4610-810a-83a727a1f62d.png)

**Comment by edbird** [comment]
This also happens with a new install of QMK MSYS. Installed on a windows 10 machine the other day and this exact error occurred when trying to compile a default keyboard layout.

**Comment by edbird** [comment]
Seems like this bug has been open for quite some time - is there any indication that someone might address the problem in the near future? Is there any solution/workaround known?

**Comment by DrL3cter** [comment]
Hey edbird,

After a few days I tried to delete some keyboard projects and recompile the layout. It seems that there is a limit for keyboards and/or keymaps.
After deleting like 10 example keyboards everything worked just fine.
Let me know if this worked for you too.

**Comment by edbird** [comment]
@DrL3cter Thanks for the info.

To clarify, what should I do? Go into the `qmk_firmware/keyboards` folder and just delete a selection of the folders in that directory?

What I don't understand is surely there are many people who have this problem after running `qmk setup` from `QMK MSYS`. So why isn't this a more widely known about issue? It can't surely be a rare thing, since these keyboard maps come with qmk by default.

**Comment by edbird** [comment]
I tried deleting a bunch of folders starting with a, then b, etc, got all the way to e. Each time I appeared to be getting a different error.

Now the process appears to be stuck with:

```
/usr/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/usr/bin/sh: -c: line 2: syntax error: unexpected end of file
gmake[1]: *** [tmk_core/rules.mk:438: .build/obj_kbdfans_kbd67_rev2_default/obj.txt] Error 2
Make finished with errors
gmake: *** [Makefile:478: kbdfans/kbd67/rev2:default] Error 1
```

**Comment by DrL3cter** [comment]
After reinstalling QMK I did the following before I compiled the first keyboard.
In my qmk_firmware/keyboards folder I deleted ten keyboard folders. After that I compiled my keyboard and everything went through without any errors. 

If you want to compile the kbd67 keyboard it seems that you are missing a ' in your obj.txt

I just can tell you what worked for me.
You could try this with a freshly installed QMK with QMK Firmware Version 0.14.6
![image](https://user-images.githubusercontent.com/91549295/152840255-7aae1a43-6e19-4bf8-9ee2-97a28369d235.png)

**Comment by edbird** [comment]
It seems that the obj.txt file is part of the generated files from the build, so presumably I shouldn't be editing them?

What did you do to reinstall qmk? Delete the git repository folder, then uninstall/reinstall QMK MSYS?

**Comment by edbird** [comment]
Notes: May be cause by selecting "no" when asked by qmk setup to download git repo on first run?

**Comment by edbird** [comment]
Notes: Tried uninstalling QMK MSYS, then re-downloading and installing with default options. Same issue as before.

**Comment by DrL3cter** [comment]
Hey. I uninstalled QMK and deleted the git repo. After that, I downloaded the git repo and reinstalled everything, and removed a few keyboards. I don't know which settings I used because when no errors occurred while compiling I tried to change as little as possible.
You can try to not download the repo on the first run.

**Comment by edbird** [comment]
Hmm strange. I've just tried moving all the keyboards beginning with the letter B to a different folder - which I assume is somehow reducing the compiler load... However same issue. I did also delete the git repo (qmk_firmware) folder before re-installing...

**Comment by DrL3cter** [comment]
I would try it myself again but I have a working QMK version at the moment and don't want to "destroy" it by reinstalling it. Maybe someday a dev or mod could write a reliable solution in here. It seems that I can't help you anymore... :(

**Comment by edbird** [comment]
That's ok thanks for your help. Don't feel you have to reply - I will just post any information or notes here that might be useful to devs

**Comment by f-eq-ma** [comment]
Curious if this issue could be caused by low user limits in the QMK MSYS environment[1].  To get my compile to work, I had to remove the c*, m*, and handwired keyboards.  I looked around the QMK MSYS, but could not find any means to adjust ulimits like I would for a RHEL setup.   It may be a compile flag with QMK MSYS itself, just not knowledgeable enough on it.

[1] 
[qmk_firmware]$ ulimit -a  
core file size              (blocks, -c) unlimited   
data seg size               (kbytes, -d) unlimited   
file size                   (blocks, -f) unlimited   
open files                          (-n) 3200        <<<<<<< potential
pipe size                (512 bytes, -p) 8           
stack size                  (kbytes, -s) 2032        <<<<<  another potential
cpu time                   (seconds, -t) unlimited   
max user processes                  (-u) 256         
virtual memory              (kbytes, -v) unlimited
